In [42]:
import pandas as pd
import numpy as np
import os
import folium

In [14]:
listOfCsvs = []
for root, dirs, files in os.walk('./csvs/'):
    for file in files: 
        if '.csv' in file:
            listOfCsvs.append(file)
        else:
            continue

In [13]:
print (listOfCsvs)

['SalesJan2009.csv', 'FL_insurance_sample.csv', 'demo_animals.csv', 'Sacramentorealestatetransactions.csv', 'SacramentocrimeJanuary2006.csv']

In [15]:
df = pd.read_csv('./csvs/Sacramentorealestatetransactions.csv',delimiter = ',')

In [16]:
df

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,Wed May 21 00:00:00 EDT 2008,59222,38.631913,-121.434879
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,Wed May 21 00:00:00 EDT 2008,68212,38.478902,-121.431028
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,Wed May 21 00:00:00 EDT 2008,68880,38.618305,-121.443839
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,Wed May 21 00:00:00 EDT 2008,69307,38.616835,-121.439146
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,Wed May 21 00:00:00 EDT 2008,81900,38.519470,-121.435768
...,...,...,...,...,...,...,...,...,...,...,...,...
980,9169 GARLINGTON CT,SACRAMENTO,95829,CA,4,3,2280,Residential,Thu May 15 00:00:00 EDT 2008,232425,38.457679,-121.359620
981,6932 RUSKUT WAY,SACRAMENTO,95823,CA,3,2,1477,Residential,Thu May 15 00:00:00 EDT 2008,234000,38.499893,-121.458890
982,7933 DAFFODIL WAY,CITRUS HEIGHTS,95610,CA,3,2,1216,Residential,Thu May 15 00:00:00 EDT 2008,235000,38.708824,-121.256803
983,8304 RED FOX WAY,ELK GROVE,95758,CA,4,2,1685,Residential,Thu May 15 00:00:00 EDT 2008,235301,38.417000,-121.397424
984,3882 YELLOWSTONE LN,EL DORADO HILLS,95762,CA,3,2,1362,Residential,Thu May 15 00:00:00 EDT 2008,235738,38.655245,-121.075915

In [45]:
df2 = pd.read_csv('./csvs/SacramentocrimeJanuary2006.csv',delimiter = ',')

In [46]:
df2

,cdatetime,address,district,beat,grid,crimedescr,ucr_ncic_code,latitude,longitude
0,1/1/06 0:00,3108 OCCIDENTAL DR,3,3C,1115,10851(A)VC TAKE VEH W/O OWNER,2404,38.550420,-121.391416
1,1/1/06 0:00,2082 EXPEDITION WAY,5,5A,1512,459 PC BURGLARY RESIDENCE,2204,38.473501,-121.490186
2,1/1/06 0:00,4 PALEN CT,2,2A,212,10851(A)VC TAKE VEH W/O OWNER,2404,38.657846,-121.462101
3,1/1/06 0:00,22 BECKFORD CT,6,6C,1443,476 PC PASS FICTICIOUS CHECK,2501,38.506774,-121.426951
4,1/1/06 0:00,3421 AUBURN BLVD,2,2A,508,459 PC BURGLARY-UNSPECIFIED,2299,38.637448,-121.384613
...,...,...,...,...,...,...,...,...,...
7579,1/31/06 23:36,26TH ST / G ST,3,3B,728,594(B)(2)(A) VANDALISM/ -$400,2999,38.577832,-121.470460
7580,1/31/06 23:40,4011 FREEPORT BLVD,4,4A,957,459 PC BURGLARY BUSINESS,2203,38.537591,-121.492591
7581,1/31/06 23:41,30TH ST / K ST,3,3C,841,TRAFFIC-ACCIDENT INJURY,5400,38.572030,-121.467012
7582,1/31/06 23:45,5303 FRANKLIN BLVD,4,4B,969,3056 PAROLE VIO - I RPT,7000,38.527187,-121.471248
7583,1/31/06 23:50,COBBLE COVE LN / COBBLE SHORES DR,4,4C,1294,TRAFFIC-ACCIDENT-NON INJURY,5400,38.479628,-121.528634